<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <NoWarn>$(NoWarn);CS1591;CA1416</NoWarn>
    <Authors>Saleh Yusefnejad</Authors>
    <Company>BlazorImage</Company>
    <Product>BlazorImage</Product>
    <Copyright>Copyright (c) 2026 Saleh Yusefnejad</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/msynk/BlazorImage</PackageProjectUrl>
    <RepositoryUrl>https://github.com/msynk/BlazorImage</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <VersionPrefix>0.1.0</VersionPrefix>
    <PackageTags>blazor;image;canvas;crop;resize;webp;avif;exif;annotation;editor;wasm</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>
</Project>
